"""
================================================================================
test_sounds.py  —  DON'T LOOK AWAY  |  Procedural Sound Engine Tester
================================================================================
Run this script to hear all the new procedural horror sounds generated by sound.py:

    python3 test_sounds.py

Controls:
    1–9, 0, -, =   Play a specific sound
    SPACE           Play next sound in list
    R               Replay the last sound
    ESC / Q         Quit
================================================================================
"""

import math
import os
import sys
import time
import pygame

# Import procedural audio manager directly from sound.py
from sound import AudioManager

# Init Pygame
pygame.init()

SCREEN_W, SCREEN_H = 680, 520
screen = pygame.display.set_mode((SCREEN_W, SCREEN_H))
pygame.display.set_caption("DON'T LOOK AWAY — Procedural Sound Engine Tester")
clock = pygame.time.Clock()

# Fonts
font_big  = pygame.font.SysFont("couriernew", 22, bold=True)
font_med  = pygame.font.SysFont("couriernew", 16, bold=True)
font_sm   = pygame.font.SysFont("couriernew", 13)

# Initialize procedural audio engine
audio = AudioManager()

SOUNDS = [
    ("jumpscare",           "Shocking Jumpscare (4-stage impact)"),
    ("duck_for_jumpscare",  "Duck Silence -> Jumpscare Sequence"),
    ("ambient_hum",         "Evolving Room Ambience Drone Loop"),
    ("tension",             "High Tension Dissonant String Loop"),
    ("creature_move",       "Organic Creature Move (Random 1-4)"),
    ("whisper",             "Breathy Whispered Syllables"),
    ("heartbeat",           "Muffled Deep Heartbeat Thud"),
    ("footstep",            "Muffled Soft Player Footstep"),
    ("door_open",           "Heavy Door Creak & Settle"),
    ("click",               "Flashlight Toggle Click"),
    ("pickup_battery",      "Battery Pickup Chime"),
    ("pickup_key",          "Key Pickup Chime"),
]

HOTKEYS = {
    pygame.K_1: 0,  pygame.K_2: 1,  pygame.K_3: 2,
    pygame.K_4: 3,  pygame.K_5: 4,  pygame.K_6: 5,
    pygame.K_7: 6,  pygame.K_8: 7,  pygame.K_9: 8,
    pygame.K_0: 9,  pygame.K_MINUS: 10, pygame.K_EQUALS: 11,
}

current_idx   = 0
last_played   = -1
status_msg    = "Press 1-0 or SPACE to test the new procedural sounds"
status_color  = (200, 200, 200)
playing_name  = ""

COLORS = {
    "bg":       (10, 8, 14),
    "panel":    (20, 18, 28),
    "border":   (80, 40, 60),
    "title":    (240, 220, 200),
    "active":   (255, 200, 80),
    "ok":       (80, 220, 120),
    "err":      (220, 70, 70),
    "dim":      (130, 120, 140),
    "key":      (140, 200, 255),
}

def draw_text(surface, text, font, color, x, y, center=False):
    surf = font.render(text, True, color)
    if center:
        x -= surf.get_width() // 2
    surface.blit(surf, (x, y))
    return surf.get_height()


def play_sound(idx):
    global last_played, status_msg, status_color, playing_name
    entry = SOUNDS[idx]
    name = entry[0]

    if name == "duck_for_jumpscare":
        status_msg = "▶  Ducking silence -> Jumpscare!"
        status_color = COLORS["active"]
        playing_name = "jumpscare"
        audio.duck_for_jumpscare()
    elif name in ["ambient_hum", "tension"]:
        audio.stop_all()
        audio.loop(name, volume=0.8 if name == "ambient_hum" else 0.4)
        status_msg = f"▶  Looping: {name}"
        status_color = COLORS["ok"]
        playing_name = name
    else:
        audio.stop_all()
        audio.play(name, volume=1.0)
        status_msg = f"▶  Playing: {name}"
        status_color = COLORS["ok"]
        playing_name = name

    last_played = idx


running = True
while running:
    dt = clock.tick(60) / 1000.0

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        elif event.type == pygame.KEYDOWN:
            if event.key in (pygame.K_ESCAPE, pygame.K_q):
                running = False

            elif event.key == pygame.K_SPACE:
                play_sound(current_idx)
                current_idx = (current_idx + 1) % len(SOUNDS)

            elif event.key == pygame.K_r:
                if last_played >= 0:
                    play_sound(last_played)

            elif event.key in HOTKEYS:
                idx = HOTKEYS[event.key]
                if idx < len(SOUNDS):
                    current_idx = idx
                    play_sound(idx)

        elif event.type == pygame.MOUSEBUTTONDOWN:
            mouse_y = event.pos[1]
            row_top = 100
            row_h   = 28
            for i in range(len(SOUNDS)):
                if row_top + i * row_h <= mouse_y < row_top + (i + 1) * row_h:
                    current_idx = i
                    play_sound(i)
                    break

    screen.fill(COLORS["bg"])

    # Header
    pygame.draw.rect(screen, COLORS["panel"], (0, 0, SCREEN_W, 60))
    pygame.draw.line(screen, COLORS["border"], (0, 60), (SCREEN_W, 60), 2)
    draw_text(screen, "DON'T LOOK AWAY — Procedural Sound Tester",
              font_big, COLORS["title"], SCREEN_W // 2, 16, center=True)

    pygame.draw.rect(screen, (15, 14, 22), (0, 61, SCREEN_W, 24))
    draw_text(screen,
              "SPACE = next   1-0/-/= = hotkey   R = replay   Click row   ESC = quit",
              font_sm, COLORS["dim"], 12, 65)

    row_top = 96
    row_h   = 28

    key_labels = ["1","2","3","4","5","6","7","8","9","0","-","="]
    for i, (name, label) in enumerate(SOUNDS):
        ry = row_top + i * row_h

        if i == current_idx:
            pygame.draw.rect(screen, (30, 25, 45), (10, ry, SCREEN_W - 20, row_h - 2))
            pygame.draw.rect(screen, COLORS["border"], (10, ry, SCREEN_W - 20, row_h - 2), 1)

        key_str = f"[{key_labels[i]}]" if i < len(key_labels) else "   "
        name_color = COLORS["active"] if name == playing_name else COLORS["title"]

        draw_text(screen, key_str, font_sm, COLORS["key"], 16, ry + 6)
        draw_text(screen, name, font_med, name_color, 65, ry + 4)
        draw_text(screen, label, font_sm, COLORS["dim"], 240, ry + 6)
        draw_text(screen, "✓ PROCEDURAL", font_sm, COLORS["ok"], 530, ry + 6)

    bar_y = SCREEN_H - 50
    pygame.draw.line(screen, COLORS["border"], (0, bar_y), (SCREEN_W, bar_y), 1)
    pygame.draw.rect(screen, COLORS["panel"], (0, bar_y + 1, SCREEN_W, 50))
    draw_text(screen, status_msg, font_med, status_color, SCREEN_W // 2, bar_y + 14, center=True)

    if playing_name and pygame.mixer.get_busy():
        pulse_r = int(55 + 30 * abs(math.sin(time.time() * 4)))
        pygame.draw.circle(screen, (pulse_r, 220, 80), (22, bar_y + 24), 6)

    pygame.display.flip()

audio.stop_all()
pygame.quit()
sys.exit()
